import { useTheme } from 'next-themes';
import Head from 'next/head';

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5">
        <button onClick={() => setTheme('light')}>set light</button>
        <br />
        <button onClick={() => setTheme('dark')}>set dark</button>
      </main>
    </>
  );
}
