import Head from 'next/head';

import BooksList from '@/components/BooksList';
import CategorySlider from '@/components/CategorySlider';

export default function Home({ bestsellers }) {
  console.log(bestsellers);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5">
        <CategorySlider />

        <BooksList data={bestsellers} title={'Bestsellers'} />

        <div className="h-screen"></div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const bestsellers = await fetch(
    'https://www.googleapis.com/books/v1/volumes?q=subject:fiction&orderBy=relevance'
  ).then((res) => res.json());

  return {
    props: {
      bestsellers,
    },
  };
}
